#
# File:    trim-sandbox-guidance.sh
# Created: 2026-08-29
# License: MIT
#
# Copyright (c) 2026 Michael Portner
#
# Rewrites the CLAUDE.md sbx generates one directory ABOVE the workspace, so
# that it carries only what sbx actually knows about the sandbox and none of
# the project guidance it invents.
#
# Why this exists. sbx writes an AI profile file at the parent of the workspace
# (sbx 0.39.0; verified on a throwaway sandbox). Claude Code walks up from the
# working directory when it discovers instruction files, so that file loads
# alongside the repository's own CLAUDE.md, at a scope the repository cannot
# override and where nobody working on the project can see or review it.
#
# Its first sections are generated by guessing from the file extensions in the
# workspace: a package manager, build, test and lint commands, a coding style.
# On a pnpm workspace it instructs the agent to run `npm install`, which is not
# a style difference, it corrupts the workspace. The rest of the file, from
# `## Environment Persistence` on, is the part sbx is authoritative about: the
# persistent environment file, egress filtering, how git authenticates, direct
# versus clone workspace mode, and the pointer to each kit's own instructions.
# That part is worth keeping, which is why this trims rather than deletes.
#
# It runs as a startup command on every container start and is idempotent: the
# marker on the first line is what stops the second run redoing the first one's
# work. sbx writes the file at creation only, so in practice this rewrites once
# and no-ops thereafter.
#
# Everything it declines to do is silent-and-successful by design. A missing
# file, a missing anchor, an unfamiliar first line: all leave the file exactly
# as it was. This edits a file another tool owns, so where the shape is not the
# one documented above, leaving it alone is the only safe answer.
#
# POSIX sh, run by `sh` from the kit's startup command.

set -u

MARKER='<!-- claude-config-kit: trimmed sbx project guidance -->'

# Where sbx's own sandbox content starts. Everything above it is generated
# project guidance and goes.
ANCHOR='## Environment Persistence'

# A generic block of project advice sbx appends below its own sections
# ("Run tests after making modifications", "npm, pip and uv are already
# available"). Dropped for the same reason as the header: nobody wrote it about
# this project. Its own heading is the boundary; the next `## ` heading ends it.
DROP='## Additional Notes'

note() { echo "claude-config: $*" >&2; }

# No workspace, nothing to do. Startup commands do run with the container
# environment, but this must not fail if that ever stops being true.
[ -n "${WORKSPACE_DIR:-}" ] || exit 0

target="$(dirname "$WORKSPACE_DIR")/CLAUDE.md"
[ -f "$target" ] || exit 0

first="$(head -n 1 "$target" 2>/dev/null || echo '')"

# Already done. Not an error, and not worth a line of output on every start.
[ "$first" = "$MARKER" ] && exit 0

# Anything but sbx's own generated file is left alone. A user who put their own
# CLAUDE.md there meant it.
if [ "$first" != '# Project Guidance' ]; then
  note "$target is not an sbx-generated guidance file, left untouched"
  exit 0
fi

if ! grep -q "^$ANCHOR\$" "$target"; then
  note "$target has no '$ANCHOR' section, left untouched"
  exit 0
fi

# Written beside the target so the final mv is a same-filesystem rename, which
# is atomic: a reader sees the old file or the new one, never a half-written
# mix. The trap clears the temp file on every exit path, including a failure
# part way through.
tmp="$target.trim.$$"
trap 'rm -f "$tmp" 2>/dev/null' EXIT INT TERM

{
  cat <<EOF
$MARKER
# Sandbox Guidance

sbx generates this file one directory above the workspace, so Claude Code loads
it alongside the workspace's own instruction files. It is not part of any
project, and nobody working on the project can see or review it.

What follows is the part sbx is authoritative about: the shell environment,
network egress, git authentication, the workspace mode, and the kits installed
here. It carries no project conventions.

The instruction files inside the workspace are the authority on how this
project is built, tested and tooled, including which package manager to use.
Where anything here appears to contradict them, they win.

The sections above this line were removed by claude-config-kit. They were
generated by guessing from the workspace's file extensions and asserted build
and package manager commands that nobody had checked against this project.

EOF

  # Fences are tracked so a "## ..." line inside a code block is content, not a
  # heading: the persistent-environment section quotes exactly that shape.
  awk -v anchor="$ANCHOR" -v drop="$DROP" '
    BEGIN { started = 0; skipping = 0; fence = 0 }
    {
      if (substr($0, 1, 3) == "```") { fence = !fence }
      is_h2 = (!fence && substr($0, 1, 3) == "## ")
      if (!started) {
        if (is_h2 && $0 == anchor) { started = 1 } else { next }
      }
      if (is_h2) { skipping = ($0 == drop) }
      if (!skipping) { print }
    }
  ' "$target"
} > "$tmp" || { note "could not rewrite $target, left untouched"; exit 0; }

# An empty result means the awk above matched nothing it expected to; keeping
# the original is better than replacing it with nothing.
[ -s "$tmp" ] || { note "rewrite of $target came out empty, left untouched"; exit 0; }

if mv "$tmp" "$target"; then
  note "trimmed the generated project guidance from $target"
else
  note "could not replace $target, left untouched"
fi

exit 0
